# Generated by Django 2.1.7 on 2019-07-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20190728_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='person',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AddField(
            model_name='education',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='education_level',
            field=models.CharField(choices=[('HS', 'High School'), ('AA', "Associate's of Arts"), ('AS', "Associate's of Science"), ('BA', "Bachelor's of Arts"), ('BS', "Bachelor's of Science"), ('MA', "Master's of Arts"), ('MS', "Master's of Science"), ('PhD', 'Doctorate Degree'), ('O', 'Other')], default=None, max_length=20),
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
