# Generated by Django 2.1.7 on 2019-07-29 22:35

from django.db import migrations
import partial_date.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20190729_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=partial_date.fields.PartialDateField(blank=True, null=True, verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=partial_date.fields.PartialDateField(blank=True, null=True, verbose_name='start_date'),
        ),
    ]
